"""CER application foundation: baseline schema

Revision ID: 0001_foundation
Revises:
Create Date: 2026-09-15

Esquema inicial y único de la base reutilizable. **No arrastra la historia de
migraciones de Staffing**: se generó con `alembic revision --autogenerate`
contra una base PostgreSQL vacía a partir de los modelos retenidos, y se le
añadieron a mano los objetos que el autogenerate no infiere (disparadores).

Qué contiene
------------
* Tenant, identidad y RBAC: `company`, `company_state`, `region`, `user`,
  `user_company`, `role`, `permission`, `role_permission`,
  `role_permission_change_request`.
* Auditoría: `audit_event` (append-only).
* Plataforma: `platform_integration`, `platform_secret`, `platform_policy`,
  `platform_audit_event` (append-only), `platform_health_check`,
  `platform_health_check_run` (append-only).
* Integración entre aplicaciones: `webhook_endpoint`, `webhook_delivery`,
  `integration_event` (append-only), `idempotency_record`.

Append-only de verdad: por cada tabla, una función y dos disparadores que
rechazan `UPDATE`, `DELETE` y `TRUNCATE`. El de `TRUNCATE` va aparte porque esa
sentencia no dispara los de fila. `app/core/platform/integrity.py` comprueba en
vivo que estén instalados y activos.

Una aplicación de dominio añade sus tablas en migraciones posteriores que
revisan a esta (ver docs/DEVELOPMENT_WORKFLOW.md, disciplina de migraciones).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

#: Tablas append-only: una función y dos disparadores por tabla.
APPEND_ONLY_TABLES: tuple[str, ...] = (
    "audit_event",
    "integration_event",
    "platform_audit_event",
    "platform_health_check_run",
)

# revision identifiers, used by Alembic.
revision: str = '0001_foundation'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('subdomain', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_primary_color', sa.String(length=7), nullable=True),
    sa.Column('brand_secondary_color', sa.String(length=7), nullable=True),
    sa.Column('pdf_text_color', sa.String(length=7), nullable=True),
    sa.Column('pdf_muted_text_color', sa.String(length=7), nullable=True),
    sa.Column('pdf_surface_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_company_domain'), 'company', ['domain'], unique=True)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_subdomain'), 'company', ['subdomain'], unique=True)
    op.create_table('idempotency_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'company_id', 'key', name='uq_idempotency_record_scope_key')
    )
    op.create_index('ix_idempotency_record_expires', 'idempotency_record', ['expires_at'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gender', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_reset_token_hash'), 'user', ['reset_token_hash'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=60), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_actor_user_id'), 'audit_event', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_event_company_id'), 'audit_event', ['company_id'], unique=False)
    op.create_index('ix_audit_event_entity', 'audit_event', ['company_id', 'entity_type', 'entity_id', 'id'], unique=False)
    op.create_index(op.f('ix_audit_event_id'), 'audit_event', ['id'], unique=False)
    op.create_index('ix_audit_event_request', 'audit_event', ['request_id'], unique=False)
    op.create_table('company_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['region.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'state_id', name='uq_company_state_company_state')
    )
    op.create_index(op.f('ix_company_state_company_id'), 'company_state', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_state_id'), 'company_state', ['id'], unique=False)
    op.create_index(op.f('ix_company_state_state_id'), 'company_state', ['state_id'], unique=False)
    op.create_index('uq_company_state_single_main', 'company_state', ['company_id'], unique=True, postgresql_where=sa.text('is_main AND is_active'))
    op.create_table('platform_audit_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_audit_event_target', 'platform_audit_event', ['target', 'id'], unique=False)
    op.create_table('platform_health_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_key', sa.String(length=100), nullable=False),
    sa.Column('last_status', sa.String(length=30), nullable=False),
    sa.Column('last_detail', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(capability_key)) > 0', name='ck_platform_health_key_present'),
    sa.ForeignKeyConstraint(['last_checked_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability_key')
    )
    op.create_table('platform_health_check_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('capability_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.CheckConstraint("trigger IN ('manual', 'scheduled', 'verify')", name='ck_platform_health_check_run_trigger'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_health_check_run_key', 'platform_health_check_run', ['capability_key', 'id'], unique=False)
    op.create_table('platform_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(key)) > 0', name='ck_platform_integration_key_present'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('platform_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(key)) > 0', name='ck_platform_policy_key_present'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), server_default=sa.text("'operative'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('management', 'operative')", name='ck_role_category'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_role_company_name'),
    sa.UniqueConstraint('id', 'company_id', name='uq_role_id_company')
    )
    op.create_index(op.f('ix_role_category'), 'role', ['category'], unique=False)
    op.create_index(op.f('ix_role_company_id'), 'role', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('webhook_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('counterpart_app', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('secret_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('secret_key_id', sa.String(length=64), nullable=False),
    sa.Column('secret_rotated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_webhook_endpoint_direction'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_webhook_endpoint_company_name'),
    sa.UniqueConstraint('public_id', name='uq_webhook_endpoint_public_id')
    )
    op.create_index('ix_webhook_endpoint_company_direction', 'webhook_endpoint', ['company_id', 'direction', 'is_active'], unique=False)
    op.create_table('integration_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('counterpart_app', sa.String(length=80), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_integration_event_direction'),
    sa.CheckConstraint("status IN ('accepted', 'unhandled', 'duplicate', 'rejected', 'queued')", name='ck_integration_event_status'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoint.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_event_company_time', 'integration_event', ['company_id', 'occurred_at'], unique=False)
    op.create_index('ix_integration_event_correlation', 'integration_event', ['correlation_id'], unique=False)
    op.create_index('ix_integration_event_lookup', 'integration_event', ['endpoint_id', 'event_id'], unique=False)
    op.create_table('platform_secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_id', sa.String(length=16), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('set_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_platform_secret_name_present'),
    sa.CheckConstraint('octet_length(nonce) = 12', name='ck_platform_secret_nonce_12'),
    sa.ForeignKeyConstraint(['integration_id'], ['platform_integration.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'name', name='uq_platform_secret_slot')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_permission')
    )
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=False)
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('role_permission_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_permission_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_change_request_status'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id', 'company_id'], ['role.id', 'role.company_id'], name='fk_change_request_role_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_request_company', 'role_permission_change_request', ['company_id'], unique=False)
    op.create_index(op.f('ix_role_permission_change_request_id'), 'role_permission_change_request', ['id'], unique=False)
    op.create_index(op.f('ix_role_permission_change_request_requested_by_user_id'), 'role_permission_change_request', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_role_permission_change_request_reviewed_by_user_id'), 'role_permission_change_request', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_role_permission_change_request_role_id'), 'role_permission_change_request', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permission_change_request_status'), 'role_permission_change_request', ['status'], unique=False)
    op.create_index('uq_change_request_one_pending_per_role', 'role_permission_change_request', ['role_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id', 'company_id'], ['role.id', 'role.company_id'], name='fk_user_company_role_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_user_company')
    )
    op.create_index(op.f('ix_user_company_company_id'), 'user_company', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_company_id'), 'user_company', ['id'], unique=False)
    op.create_index('ix_user_company_role_id', 'user_company', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_company_user_id'), 'user_company', ['user_id'], unique=False)
    op.create_table('webhook_delivery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_status_code', sa.SmallInteger(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'failed')", name='ck_webhook_delivery_status'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoint.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'event_id', name='uq_webhook_delivery_endpoint_event')
    )
    op.create_index('ix_webhook_delivery_due', 'webhook_delivery', ['status', 'next_attempt_at'], unique=False)

    for tabla in APPEND_ONLY_TABLES:
        op.execute(
            f"""
            CREATE OR REPLACE FUNCTION {tabla}_is_append_only()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION '{tabla} is append-only: % is not allowed', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{tabla}_append_only
            BEFORE UPDATE OR DELETE ON {tabla}
            FOR EACH ROW EXECUTE FUNCTION {tabla}_is_append_only();
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{tabla}_no_truncate
            BEFORE TRUNCATE ON {tabla}
            FOR EACH STATEMENT EXECUTE FUNCTION {tabla}_is_append_only();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for tabla in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tabla}_no_truncate ON {tabla}")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tabla}_append_only ON {tabla}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_delivery_due', table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    op.drop_index(op.f('ix_user_company_user_id'), table_name='user_company')
    op.drop_index('ix_user_company_role_id', table_name='user_company')
    op.drop_index(op.f('ix_user_company_id'), table_name='user_company')
    op.drop_index(op.f('ix_user_company_company_id'), table_name='user_company')
    op.drop_table('user_company')
    op.drop_index('uq_change_request_one_pending_per_role', table_name='role_permission_change_request', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_role_permission_change_request_status'), table_name='role_permission_change_request')
    op.drop_index(op.f('ix_role_permission_change_request_role_id'), table_name='role_permission_change_request')
    op.drop_index(op.f('ix_role_permission_change_request_reviewed_by_user_id'), table_name='role_permission_change_request')
    op.drop_index(op.f('ix_role_permission_change_request_requested_by_user_id'), table_name='role_permission_change_request')
    op.drop_index(op.f('ix_role_permission_change_request_id'), table_name='role_permission_change_request')
    op.drop_index('ix_change_request_company', table_name='role_permission_change_request')
    op.drop_table('role_permission_change_request')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_table('platform_secret')
    op.drop_index('ix_integration_event_lookup', table_name='integration_event')
    op.drop_index('ix_integration_event_correlation', table_name='integration_event')
    op.drop_index('ix_integration_event_company_time', table_name='integration_event')
    op.drop_table('integration_event')
    op.drop_index('ix_webhook_endpoint_company_direction', table_name='webhook_endpoint')
    op.drop_table('webhook_endpoint')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_company_id'), table_name='role')
    op.drop_index(op.f('ix_role_category'), table_name='role')
    op.drop_table('role')
    op.drop_table('platform_policy')
    op.drop_table('platform_integration')
    op.drop_index('ix_platform_health_check_run_key', table_name='platform_health_check_run')
    op.drop_table('platform_health_check_run')
    op.drop_table('platform_health_check')
    op.drop_index('ix_platform_audit_event_target', table_name='platform_audit_event')
    op.drop_table('platform_audit_event')
    op.drop_index('uq_company_state_single_main', table_name='company_state', postgresql_where=sa.text('is_main AND is_active'))
    op.drop_index(op.f('ix_company_state_state_id'), table_name='company_state')
    op.drop_index(op.f('ix_company_state_id'), table_name='company_state')
    op.drop_index(op.f('ix_company_state_company_id'), table_name='company_state')
    op.drop_table('company_state')
    op.drop_index('ix_audit_event_request', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_id'), table_name='audit_event')
    op.drop_index('ix_audit_event_entity', table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_company_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_user_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_user_reset_token_hash'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index('ix_idempotency_record_expires', table_name='idempotency_record')
    op.drop_table('idempotency_record')
    op.drop_index(op.f('ix_company_subdomain'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_domain'), table_name='company')
    op.drop_table('company')
    for tabla in APPEND_ONLY_TABLES:
        op.execute(f"DROP FUNCTION IF EXISTS {tabla}_is_append_only()")
    # ### end Alembic commands ###
