"""CER Route foundation: vehicles, supervisor profiles, assignments, standard values

Revision ID: 0002_route_foundation
Revises: 0001_foundation

Cuatro tablas del dominio de campo de CER Route (RTE02). Todas acotadas por
compañía, y con tres restricciones que **la base** garantiza porque una
comprobación en Python sólo protege mientras nadie se olvide de llamarla:

1. `uq_vehicle_assignment_current` — índice único **parcial**
   (`WHERE effective_to IS NULL`): un supervisor no puede tener dos vehículos
   vigentes a la vez. Dos peticiones simultáneas no producen dos filas
   actuales; la segunda choca contra el índice y recibe 409.

2. Las FK **compuestas** `(supervisor_profile_id, company_id)` y
   `(vehicle_id, company_id)` hacen imposible asignar el vehículo de otro
   tenant, aunque el servicio se olvidara de comprobarlo.

3. `fk_supervisor_profile_membership` apunta a `user_company(user_id,
   company_id)`: sólo puede ser supervisor de Route quien ya pertenece a la
   compañía.

Ninguna de estas tablas es append-only. `vehicle_assignment` se cierra
escribiendo `effective_to`, y un disparador append-only lo impediría; la
historia se protege no borrando filas y dejando traza en `audit_event`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_route_foundation'
down_revision: Union[str, None] = '0001_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('list_code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("list_code IN ('client_visit_activities', 'recruiting_activities', 'employee_visit_reasons', 'delivery_types', 'office_purposes', 'other_activities', 'outcomes', 'received_by')", name='ck_standard_value_list_code'),
    sa.CheckConstraint('sort_order >= 0', name='ck_standard_value_sort_order'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'list_code', 'label', name='uq_standard_value_company_list_label'),
    sa.UniqueConstraint('id', 'company_id', name='uq_standard_value_id_company')
    )
    op.create_index(op.f('ix_standard_value_company_id'), 'standard_value', ['company_id'], unique=False)
    op.create_index('ix_standard_value_company_list', 'standard_value', ['company_id', 'list_code', 'sort_order'], unique=False)
    op.create_index(op.f('ix_standard_value_id'), 'standard_value', ['id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('fuel_grade', sa.String(length=20), nullable=False),
    sa.Column('operational_mpg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("fuel_grade IN ('regular', 'midgrade', 'premium', 'diesel')", name='ck_vehicle_fuel_grade'),
    sa.CheckConstraint('operational_mpg > 0', name='ck_vehicle_operational_mpg_positive'),
    sa.CheckConstraint('year >= 1900 AND year <= 2100', name='ck_vehicle_year_range'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'unit', name='uq_vehicle_company_unit'),
    sa.UniqueConstraint('id', 'company_id', name='uq_vehicle_id_company')
    )
    op.create_index('ix_vehicle_company_active', 'vehicle', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_vehicle_company_id'), 'vehicle', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_table('supervisor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'company_id'], ['user_company.user_id', 'user_company.company_id'], name='fk_supervisor_profile_membership', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_supervisor_profile_company_user'),
    sa.UniqueConstraint('id', 'company_id', name='uq_supervisor_profile_id_company')
    )
    op.create_index(op.f('ix_supervisor_profile_company_id'), 'supervisor_profile', ['company_id'], unique=False)
    op.create_index(op.f('ix_supervisor_profile_id'), 'supervisor_profile', ['id'], unique=False)
    op.create_index(op.f('ix_supervisor_profile_user_id'), 'supervisor_profile', ['user_id'], unique=False)
    op.create_table('vehicle_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_profile_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_vehicle_assignment_period'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_profile_id', 'company_id'], ['supervisor_profile.id', 'supervisor_profile.company_id'], name='fk_vehicle_assignment_supervisor_same_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id', 'company_id'], ['vehicle.id', 'vehicle.company_id'], name='fk_vehicle_assignment_vehicle_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignment_company_id'), 'vehicle_assignment', ['company_id'], unique=False)
    op.create_index('ix_vehicle_assignment_history', 'vehicle_assignment', ['company_id', 'supervisor_profile_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_vehicle_assignment_id'), 'vehicle_assignment', ['id'], unique=False)
    op.create_index('ix_vehicle_assignment_vehicle', 'vehicle_assignment', ['company_id', 'vehicle_id'], unique=False)
    op.create_index('uq_vehicle_assignment_current', 'vehicle_assignment', ['company_id', 'supervisor_profile_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vehicle_assignment_current', table_name='vehicle_assignment', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index('ix_vehicle_assignment_vehicle', table_name='vehicle_assignment')
    op.drop_index(op.f('ix_vehicle_assignment_id'), table_name='vehicle_assignment')
    op.drop_index('ix_vehicle_assignment_history', table_name='vehicle_assignment')
    op.drop_index(op.f('ix_vehicle_assignment_company_id'), table_name='vehicle_assignment')
    op.drop_table('vehicle_assignment')
    op.drop_index(op.f('ix_supervisor_profile_user_id'), table_name='supervisor_profile')
    op.drop_index(op.f('ix_supervisor_profile_id'), table_name='supervisor_profile')
    op.drop_index(op.f('ix_supervisor_profile_company_id'), table_name='supervisor_profile')
    op.drop_table('supervisor_profile')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_company_id'), table_name='vehicle')
    op.drop_index('ix_vehicle_company_active', table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_standard_value_id'), table_name='standard_value')
    op.drop_index('ix_standard_value_company_list', table_name='standard_value')
    op.drop_index(op.f('ix_standard_value_company_id'), table_name='standard_value')
    op.drop_table('standard_value')
    # ### end Alembic commands ###
