"""CER Route work session domain

Revision ID: 0003_work_session
Revises: 0002_route_foundation

La Jornada del supervisor (RTE03): `none -> ACTIVE -> ENDED`, sin Trip ni
Activity todavía. Una sola tabla, con dos garantías que sostiene la base y no
el código Python:

1. `uq_work_session_one_active` — índice único **parcial**
   (`WHERE status = 'active'`): un supervisor no puede tener dos jornadas
   vigentes a la vez. Dos peticiones de `Start Work` simultáneas no producen
   dos filas `ACTIVE`; la segunda choca contra el índice y el servicio relee
   la que ganó, en vez de fallar (ver `WorkSessionService.start`).

2. `fk_work_session_vehicle_same_company` — clave foránea **compuesta**
   `(vehicle_id, company_id)`: hace imposible que la jornada apunte a un
   vehículo de otro tenant, con o sin bug en el servicio.

`session_date`, `vehicle_id` y `mpg_snapshot` son snapshot histórico: se
escriben una vez al crear la fila y ningún camino de este módulo los vuelve a
tocar. `started_at`/`ended_at` son el reloj del servidor, autoritativo; las
columnas `*_device_captured_at` y `*_utc_offset_minutes` son evidencia del
dispositivo, nunca fuente de verdad (D-10).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_work_session'
down_revision: Union[str, None] = '0002_route_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_device_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_utc_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('end_device_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_utc_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('mpg_snapshot', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'ended')", name='ck_work_session_status'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id', 'company_id'], ['vehicle.id', 'vehicle.company_id'], name='fk_work_session_vehicle_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_work_session_id_company')
    )
    op.create_index(op.f('ix_work_session_company_id'), 'work_session', ['company_id'], unique=False)
    op.create_index('ix_work_session_company_user_date', 'work_session', ['company_id', 'user_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_work_session_id'), 'work_session', ['id'], unique=False)
    op.create_index(op.f('ix_work_session_user_id'), 'work_session', ['user_id'], unique=False)
    op.create_index('uq_work_session_one_active', 'work_session', ['company_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_work_session_one_active', table_name='work_session', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_work_session_user_id'), table_name='work_session')
    op.drop_index(op.f('ix_work_session_id'), table_name='work_session')
    op.drop_index('ix_work_session_company_user_date', table_name='work_session')
    op.drop_index(op.f('ix_work_session_company_id'), table_name='work_session')
    op.drop_table('work_session')
    # ### end Alembic commands ###
