"""CER Route admin lifecycle: delete distinto de deactivate

Revision ID: 0004_admin_lifecycle
Revises: 0003_work_session

El addendum RTE02-A01 separa dos acciones que hasta ahora eran la misma:
**desactivar** (retirar del uso operativo, reversible, visible en la
administración) y **borrar** (sacar de la experiencia normal del administrador).

Por qué lápida y no `DELETE`
-----------------------------
El borrado físico no estaba disponible, y no es una preferencia:

* `work_session.vehicle_id` y `vehicle_assignment.vehicle_id` referencian
  `vehicle` con `RESTRICT` — PostgreSQL rechaza borrar un vehículo con historia.
* `vehicle_assignment.supervisor_profile_id` referencia `supervisor_profile` con
  `CASCADE` — un `DELETE` físico del perfil se llevaría por delante todo el
  historial de asignaciones de esa persona.
* `standard_value.id` lo referenciarán las actividades de RTE04/RTE05.
* `supervisor_profile` referencia `user_company` con `CASCADE` — borrar
  físicamente una pertenencia se llevaría la designación de Route de esa
  persona y, tras ella, su historial de vehículos.

Así que `deleted_at` marca la fila y toda consulta de la experiencia normal
filtra `deleted_at IS NULL`. Ver `app/core/models/SoftDelete.py`.

Las tres únicas pasan a ser parciales
--------------------------------------
`uq_vehicle_company_unit`, `uq_standard_value_company_list_label` y
`uq_supervisor_profile_company_user` se convierten en índices únicos
**parciales** (`WHERE deleted_at IS NULL`). Sin esto, borrar "V-014" impediría
dar de alta otro "V-014" para siempre: el administrador chocaría contra un
conflicto con una fila que para él ya no existe.

`uq_standard_value_company_seed_key` es la excepción y **no** es parcial, a
propósito: la huella de la siembra tiene que sobrevivir al borrado, porque es
exactamente lo que impide que el siguiente aprovisionamiento resucite un valor
que el administrador quitó.

Interpretación de los datos existentes
---------------------------------------
Ninguna fila se reinterpreta. `deleted_at` nace `NULL` en todas: nada estaba
borrado antes porque el borrado no existía, así que todo lo que hay se conserva
tal cual, activo o desactivado según su `is_active`. `seed_key` nace `NULL`
también: los valores que ya existan se consideran del tenant, no sembrados, y
por tanto el aprovisionamiento no los tocará nunca.

Límite conocido del `downgrade`: rehace las únicas completas, así que falla si
para entonces existen filas con lápida que colisionen entre sí (dos "V-014", uno
borrado y otro vivo). Es correcto que falle — deshacer el esquema no puede
decidir por su cuenta cuál de las dos filas sobra.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_admin_lifecycle'
down_revision: Union[str, None] = '0003_work_session'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_value', sa.Column('seed_key', sa.String(length=80), nullable=True))
    op.add_column('standard_value', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_standard_value_company_list_label'), 'standard_value', type_='unique')
    op.create_index('uq_standard_value_company_list_label', 'standard_value', ['company_id', 'list_code', 'label'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('uq_standard_value_company_seed_key', 'standard_value', ['company_id', 'seed_key'])
    op.add_column('supervisor_profile', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_supervisor_profile_company_user'), 'supervisor_profile', type_='unique')
    op.create_index('uq_supervisor_profile_company_user', 'supervisor_profile', ['company_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('vehicle', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_vehicle_company_unit'), 'vehicle', type_='unique')
    op.create_index('uq_vehicle_company_unit', 'vehicle', ['company_id', 'unit'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # `user_company`: retirar a alguien de un tenant es borrar su pertenencia,
    # no su identidad. `uq_user_company_user_company` se deja **completa** a
    # propósito — ver el docstring del modelo: hacerla parcial habilitaría una
    # reincorporación de identidad, que este addendum difiere explícitamente.
    op.add_column('user_company', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_company', 'deleted_at')
    op.drop_index('uq_vehicle_company_unit', table_name='vehicle', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_vehicle_company_unit'), 'vehicle', ['company_id', 'unit'], postgresql_nulls_not_distinct=False)
    op.drop_column('vehicle', 'deleted_at')
    op.drop_index('uq_supervisor_profile_company_user', table_name='supervisor_profile', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_supervisor_profile_company_user'), 'supervisor_profile', ['company_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('supervisor_profile', 'deleted_at')
    op.drop_constraint('uq_standard_value_company_seed_key', 'standard_value', type_='unique')
    op.drop_index('uq_standard_value_company_list_label', table_name='standard_value', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_standard_value_company_list_label'), 'standard_value', ['company_id', 'list_code', 'label'], postgresql_nulls_not_distinct=False)
    op.drop_column('standard_value', 'deleted_at')
    op.drop_column('standard_value', 'seed_key')
    # ### end Alembic commands ###
