"""CER Route trip domain

Revision ID: 0005_trip_domain
Revises: 0004_admin_lifecycle

El desplazamiento real dentro de la jornada (RTE04-C1). Dos tablas y tres
garantías que sostiene la base, no el codigo Python:

1. `uq_trip_one_non_terminal` — indice unico **parcial**
   (`WHERE status NOT IN ('closed','interrupted')`): un supervisor no puede
   tener dos viajes vivos a la vez. `ARRIVED` cuenta como vivo a proposito: un
   viaje operativo que llego sigue esperando a RTE05, y confundir llegar con
   terminar es justo lo que la instruccion prohibe.

2. `fk_trip_work_session_same_company` — clave foranea **compuesta**
   `(work_session_id, company_id)`: hace imposible que un viaje cuelgue de la
   jornada de otro tenant, con o sin bug en el servicio.

3. `fk_trip_*_standard_value_same_company` con `RESTRICT` — un valor de lista
   borrado por el administrador no puede llevarse por delante el viaje que lo
   eligio. RTE02-A01 dejo esos borrados como lapida, asi que la fila sigue
   existiendo y el historico se resuelve.

El plan original no se pisa
----------------------------
`original_purpose`, `original_context_reference` y `original_standard_value_id`
se escriben una vez y ningun camino del modulo los vuelve a tocar. Cada
`Change Plan` **apila** una fila en `trip_purpose_change` en vez de sobrescribir,
que es lo que permite reconstruir despues plan original -> cambios -> plan final.

El valor estandarizado de pre-viaje
------------------------------------
Solo tres contextos lo llevan, y lo fijo CER en la resolucion 002:
`employee_visit` (Reason), `check_delivery` (Delivery Type) y `office`
(Office Purpose). Los demas valores de lista describen lo que se ejecuto al
llegar y son de RTE05. La correspondencia vive en `PRETRIP_STANDARD_LIST` y la
valida el servicio: un valor de otra lista se rechaza con 422.

Interpretacion de datos existentes: ninguna. Son tablas nuevas y vacias.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_trip_domain'
down_revision: Union[str, None] = '0004_admin_lifecycle'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='planning', nullable=False),
    sa.Column('original_purpose', sa.String(length=30), nullable=False),
    sa.Column('original_context_reference', sa.Text(), nullable=True),
    sa.Column('current_purpose', sa.String(length=30), nullable=False),
    sa.Column('current_context_reference', sa.Text(), nullable=True),
    sa.Column('original_standard_value_id', sa.Integer(), nullable=True),
    sa.Column('current_standard_value_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("current_purpose IN ('client_visit', 'recruiting', 'employee_visit', 'check_delivery', 'office', 'other', 'home')", name='ck_trip_current_purpose'),
    sa.CheckConstraint("original_purpose IN ('client_visit', 'recruiting', 'employee_visit', 'check_delivery', 'office', 'other', 'home')", name='ck_trip_original_purpose'),
    sa.CheckConstraint("status IN ('planning', 'in_transit', 'arrived', 'closed', 'interrupted')", name='ck_trip_status'),
    sa.CheckConstraint('arrived_at IS NULL OR started_at IS NULL OR arrived_at >= started_at', name='ck_trip_arrived_after_started'),
    sa.CheckConstraint('sequence >= 1', name='ck_trip_sequence_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_standard_value_id', 'company_id'], ['standard_value.id', 'standard_value.company_id'], name='fk_trip_current_standard_value_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_standard_value_id', 'company_id'], ['standard_value.id', 'standard_value.company_id'], name='fk_trip_original_standard_value_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_session_id', 'company_id'], ['work_session.id', 'work_session.company_id'], name='fk_trip_work_session_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_trip_id_company'),
    sa.UniqueConstraint('work_session_id', 'sequence', name='uq_trip_session_sequence')
    )
    op.create_index(op.f('ix_trip_company_id'), 'trip', ['company_id'], unique=False)
    op.create_index('ix_trip_company_session', 'trip', ['company_id', 'work_session_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_trip_id'), 'trip', ['id'], unique=False)
    op.create_index(op.f('ix_trip_work_session_id'), 'trip', ['work_session_id'], unique=False)
    op.create_index('uq_trip_one_non_terminal', 'trip', ['company_id', 'work_session_id'], unique=True, postgresql_where=sa.text("status NOT IN ('closed', 'interrupted')"))
    op.create_table('trip_purpose_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('from_purpose', sa.String(length=30), nullable=False),
    sa.Column('from_context_reference', sa.Text(), nullable=True),
    sa.Column('from_standard_value_id', sa.Integer(), nullable=True),
    sa.Column('to_purpose', sa.String(length=30), nullable=False),
    sa.Column('to_context_reference', sa.Text(), nullable=True),
    sa.Column('to_standard_value_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_purpose IN ('client_visit', 'recruiting', 'employee_visit', 'check_delivery', 'office', 'other', 'home')", name='ck_trip_purpose_change_from'),
    sa.CheckConstraint("to_purpose IN ('client_visit', 'recruiting', 'employee_visit', 'check_delivery', 'office', 'other', 'home')", name='ck_trip_purpose_change_to'),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id', 'company_id'], ['trip.id', 'trip.company_id'], name='fk_trip_purpose_change_trip_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_purpose_change_company_id'), 'trip_purpose_change', ['company_id'], unique=False)
    op.create_index(op.f('ix_trip_purpose_change_id'), 'trip_purpose_change', ['id'], unique=False)
    op.create_index('ix_trip_purpose_change_trip', 'trip_purpose_change', ['company_id', 'trip_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_trip_purpose_change_trip_id'), 'trip_purpose_change', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_purpose_change_trip_id'), table_name='trip_purpose_change')
    op.drop_index('ix_trip_purpose_change_trip', table_name='trip_purpose_change')
    op.drop_index(op.f('ix_trip_purpose_change_id'), table_name='trip_purpose_change')
    op.drop_index(op.f('ix_trip_purpose_change_company_id'), table_name='trip_purpose_change')
    op.drop_table('trip_purpose_change')
    op.drop_index('uq_trip_one_non_terminal', table_name='trip', postgresql_where=sa.text("status NOT IN ('closed', 'interrupted')"))
    op.drop_index(op.f('ix_trip_work_session_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_id'), table_name='trip')
    op.drop_index('ix_trip_company_session', table_name='trip')
    op.drop_index(op.f('ix_trip_company_id'), table_name='trip')
    op.drop_table('trip')
    # ### end Alembic commands ###
