"""CER Route odometer evidence

Revision ID: 0006_odometer_evidence
Revises: 0005_trip_domain

La evidencia de odometro de la jornada (RTE04-C3/C4). Es evidencia de la
jornada y su vehiculo, **no millaje oficial**: nada de aqui alimenta, sustituye
ni corrige el millaje de ruta, que es un dominio futuro y distinto.

Dos tablas y cuatro garantias de la base:

1. `uq_odometer_evidence_session_type` — una sola lectura por jornada y extremo.
   No hay dos lecturas de inicio compitiendo por ser la buena.

2. `uq_odometer_exception_open` — indice unico **parcial**
   (`WHERE status IN ('requested','approved')`): una sola solicitud viva por
   jornada y extremo. Pedirla dos veces no abre dos puertas.

3. `fk_odometer_evidence_vehicle_same_company` con `RESTRICT` — borrar un
   vehiculo del maestro no puede llevarse por delante la evidencia de lo que se
   condujo con el. RTE02-A01 dejo esos borrados como lapida, asi que la fila
   sigue resolviendo.

4. FK compuestas `(work_session_id, company_id)` y `(vehicle_id, company_id)` —
   hacen imposible que una evidencia cuelgue de la jornada o del vehiculo de
   otro tenant, con o sin bug en el servicio.

Por que los metadatos del fichero viven en la fila de evidencia
----------------------------------------------------------------
El repositorio tiene primitivas de almacenamiento pero ningun registro de
ficheros, y RTE04 es su primer consumidor. Crear un registro generico de
plataforma para un solo consumidor seria meter un dominio nuevo en el nucleo,
que la resolucion 003 prohibe de forma explicita. Asi que `storage_key`,
`content_hash`, `content_type` y `byte_size` se guardan aqui. La foto nunca
tiene URL publica: se sirve por un endpoint que comprueba tenant y propiedad.

La sugerencia del OCR y la lectura confirmada son columnas distintas a
proposito: se puede saber que vio la maquina y que confirmo la persona. El OCR
es asistivo y nunca establece por si solo un hecho de millaje.

`evidence_method` conserva para siempre si hubo foto o no: una lectura tecleada
sin foto no puede parecer evidencia fotografica despues, por mucho que un
administrador la autorizara.

Interpretacion de datos existentes: ninguna. Son tablas nuevas y vacias.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_odometer_evidence'
down_revision: Union[str, None] = '0005_trip_domain'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odometer_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('evidence_method', sa.String(length=20), nullable=True),
    sa.Column('confirmed_reading', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('ocr_detected_reading', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("evidence_method IN ('photo', 'manual_no_photo')", name='ck_odometer_evidence_method'),
    sa.CheckConstraint("evidence_type IN ('start', 'end')", name='ck_odometer_evidence_type'),
    sa.CheckConstraint("status IN ('pending', 'photo_confirmed', 'exception_requested', 'exception_approved', 'manual_exception_confirmed', 'not_required')", name='ck_odometer_evidence_status'),
    sa.CheckConstraint('confirmed_reading IS NULL OR confirmed_reading >= 0', name='ck_odometer_reading_not_negative'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id', 'company_id'], ['vehicle.id', 'vehicle.company_id'], name='fk_odometer_evidence_vehicle_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_session_id', 'company_id'], ['work_session.id', 'work_session.company_id'], name='fk_odometer_evidence_session_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_odometer_evidence_id_company'),
    sa.UniqueConstraint('work_session_id', 'evidence_type', name='uq_odometer_evidence_session_type')
    )
    op.create_index(op.f('ix_odometer_evidence_company_id'), 'odometer_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_odometer_evidence_id'), 'odometer_evidence', ['id'], unique=False)
    op.create_index('ix_odometer_evidence_session', 'odometer_evidence', ['company_id', 'work_session_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_odometer_evidence_work_session_id'), 'odometer_evidence', ['work_session_id'], unique=False)
    op.create_table('odometer_exception_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='requested', nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('start', 'end')", name='ck_odometer_exception_type'),
    sa.CheckConstraint("reason IN ('camera_unavailable', 'permission_problem', 'no_usable_photo', 'other')", name='ck_odometer_exception_reason'),
    sa.CheckConstraint("status IN ('requested', 'approved', 'rejected', 'consumed')", name='ck_odometer_exception_status'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_session_id', 'company_id'], ['work_session.id', 'work_session.company_id'], name='fk_odometer_exception_session_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_odometer_exception_id_company')
    )
    op.create_index('ix_odometer_exception_pending', 'odometer_exception_request', ['company_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_odometer_exception_request_company_id'), 'odometer_exception_request', ['company_id'], unique=False)
    op.create_index(op.f('ix_odometer_exception_request_id'), 'odometer_exception_request', ['id'], unique=False)
    op.create_index(op.f('ix_odometer_exception_request_work_session_id'), 'odometer_exception_request', ['work_session_id'], unique=False)
    op.create_index('uq_odometer_exception_open', 'odometer_exception_request', ['company_id', 'work_session_id', 'evidence_type'], unique=True, postgresql_where=sa.text("status IN ('requested', 'approved')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_odometer_exception_open', table_name='odometer_exception_request', postgresql_where=sa.text("status IN ('requested', 'approved')"))
    op.drop_index(op.f('ix_odometer_exception_request_work_session_id'), table_name='odometer_exception_request')
    op.drop_index(op.f('ix_odometer_exception_request_id'), table_name='odometer_exception_request')
    op.drop_index(op.f('ix_odometer_exception_request_company_id'), table_name='odometer_exception_request')
    op.drop_index('ix_odometer_exception_pending', table_name='odometer_exception_request')
    op.drop_table('odometer_exception_request')
    op.drop_index(op.f('ix_odometer_evidence_work_session_id'), table_name='odometer_evidence')
    op.drop_index('ix_odometer_evidence_session', table_name='odometer_evidence')
    op.drop_index(op.f('ix_odometer_evidence_id'), table_name='odometer_evidence')
    op.drop_index(op.f('ix_odometer_evidence_company_id'), table_name='odometer_evidence')
    op.drop_table('odometer_evidence')
    # ### end Alembic commands ###
