"""Evidencia de ubicacion y kilometraje oficial del viaje (RTE06-CP2 y CP3).

Revision ID: 0010_location_and_mileage
Revises: 0009_assignment_no_overlap
Create Date: 2026-09-29

Cuatro tablas, en una sola migracion
------------------------------------
`location_fix` y `missing_location_event` son de CP2; `trip_mileage` y
`trip_mileage_segment` de CP3. Van juntas porque el segmento **copia** las
coordenadas del punto —§28, para que la provenance sobreviva al purgado de la
evidencia cruda— y separarlas habria obligado a reformar las tablas de CP2 al
llegar CP3.

La correlacion es una tupla, no una tabla
-----------------------------------------
`uq_location_fix_event` y `uq_missing_location_event` son unicos sobre
`(company_id, event_kind, subject_kind, subject_id)`. §14 exige correlacion con
la accion exacta y prohibe correlacionar por proximidad de tiempo; los sujetos ya
existen y son durables (`work_session`, `trip`, `trip_purpose_change`,
`activity_execution`). Eso hace que el reenvio de la cola offline sea idempotente
por construccion (caso C6) y que varios `Change Plan` del mismo viaje queden
independientes y ordenados (§32).

Tres tablas append-only, y una con matiz
----------------------------------------
`location_fix` y `trip_mileage_segment` llevan el disparador completo del
proyecto: ni `UPDATE`, ni `DELETE`, ni `TRUNCATE`. Una coordenada capturada y un
tramo medido son hechos observados.

`missing_location_event` **no** puede ser append-only entero, y el motivo es una
tension real entre dos secciones de la instruccion: §29 la llama append-only y
§30 obliga a conservar el estado de notificacion, que por definicion avanza. Se
resuelve con un disparador **por columnas**: rechaza `DELETE` y `TRUNCATE`
siempre, y rechaza cualquier `UPDATE` que toque algo distinto de
`notification_status`, `notified_at`, `notes` o `updated_at`. El hecho queda
inmutable; la gestion del aviso puede avanzar. Inventar una segunda tabla solo
para el estado del aviso habria partido en dos un hecho que §29 describe como uno.

`trip_mileage` no es append-only, y tampoco puede serlo: tiene que pasar de
`pending_calculation` a terminal exactamente una vez. La inmutabilidad de §27 la
da la forma de la escritura —`UPDATE ... WHERE state = 'pending_calculation'`—,
no un permiso: `rowcount == 0` significa "ya era terminal". Es el patron que ya
protege la terminalizacion de actividades.

Indices revisados a mano
------------------------
El autogenerate propuso tres de mas, y se quitaron de los modelos y no solo de
aqui, para que el roundtrip siga limpio:

* `ix_location_fix_company_id` y `ix_missing_location_event_company_id` —
  `company_id` va primera en los indices compuestos de esas tablas, que ya la
  cubren.
* `ix_trip_mileage_segment_parent` sobre `(trip_mileage_id, sequence)` —
  identico al que `uq_trip_mileage_segment_sequence` crea por ser unico. Es el
  mismo duplicado que 0008 tuvo que quitar a mano.

Los `ix_*_id` sobre la clave primaria **se conservan**: son redundantes, pero los
tienen todas las tablas del proyecto porque salen de
`Column(primary_key=True, index=True)`. Quitarlos en dos tablas y no en las demas
crearia una inconsistencia que alguien "arreglaria" despues; si se quitan, se
quitan en una migracion propia que los quite en todas.

Nada que interpretar
--------------------
No toca ninguna fila existente: cuatro tablas nuevas y vacias. Los viajes ya
cerrados **no** reciben fila de `trip_mileage`, y es deliberado: fabricarles un
kilometraje exigiria waypoints que nunca se capturaron, que es justo lo que §20
prohibe. Su kilometraje no existe, y no existir es la respuesta veraz.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0010_location_and_mileage'

#: Tablas con el disparador append-only genérico de este esquema.
#:
#: A nivel de módulo y no como tupla en línea a propósito:
#: `test_every_trigger_created_by_a_migration_is_watched` deriva de aquí los
#: nombres `trg_{tabla}_append_only` y `trg_{tabla}_no_truncate` para exigir que
#: `EXPECTED_TRIGGERS` los vigile. Con la tupla en línea no los encontraba, y el
#: test lo dijo — que es para lo que está.
#:
#: `missing_location_event` no está aquí: su disparador es distinto (admite
#: `UPDATE` de los campos de notificación) y se escribe con su nombre literal
#: más abajo, que el test también reconoce.
APPEND_ONLY_TABLES: tuple[str, ...] = ("location_fix", "trip_mileage_segment")
down_revision: Union[str, None] = '0009_assignment_no_overlap'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_fix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('event_kind', sa.String(length=30), nullable=False),
    sa.Column('subject_kind', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('evidence_level', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('accuracy_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('device_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_age_seconds', sa.Integer(), nullable=True),
    sa.Column('permission_state', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_kind = 'start_work' AND subject_kind = 'work_session') OR (event_kind = 'end_work' AND subject_kind = 'work_session') OR (event_kind = 'start_trip' AND subject_kind = 'trip') OR (event_kind = 'arrived' AND subject_kind = 'trip') OR (event_kind = 'change_plan' AND subject_kind = 'trip_purpose_change') OR (event_kind = 'activity_complete' AND subject_kind = 'activity_execution') OR (event_kind = 'activity_leave' AND subject_kind = 'activity_execution')", name='ck_location_fix_event_subject'),
    sa.CheckConstraint("(evidence_level = 'degraded_cached' AND source_age_seconds IS NOT NULL) OR (evidence_level <> 'degraded_cached' AND source_age_seconds IS NULL)", name='ck_location_fix_cached_age'),
    sa.CheckConstraint("event_kind IN ('start_work', 'start_trip', 'change_plan', 'arrived', 'activity_complete', 'activity_leave', 'end_work')", name='ck_location_fix_event_kind'),
    sa.CheckConstraint("evidence_level IN ('fresh', 'degraded_cached', 'recovered')", name='ck_location_fix_evidence_level'),
    sa.CheckConstraint("subject_kind IN ('work_session', 'trip', 'trip_purpose_change', 'activity_execution')", name='ck_location_fix_subject_kind'),
    sa.CheckConstraint('accuracy_m IS NULL OR accuracy_m >= 0', name='ck_location_fix_accuracy'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90 AND longitude >= -180 AND longitude <= 180', name='ck_location_fix_coordinates'),
    sa.CheckConstraint('subject_id > 0', name='ck_location_fix_subject_id'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_session_id', 'company_id'], ['work_session.id', 'work_session.company_id'], name='fk_location_fix_session_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_fix_id'), 'location_fix', ['id'], unique=False)
    op.create_index('ix_location_fix_session', 'location_fix', ['company_id', 'work_session_id'], unique=False)
    op.create_index('uq_location_fix_event', 'location_fix', ['company_id', 'event_kind', 'subject_kind', 'subject_id'], unique=True)
    op.create_table('missing_location_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('event_kind', sa.String(length=30), nullable=False),
    sa.Column('subject_kind', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('permission_state', sa.String(length=20), nullable=True),
    sa.Column('rejected_candidate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_kind = 'start_work' AND subject_kind = 'work_session') OR (event_kind = 'end_work' AND subject_kind = 'work_session') OR (event_kind = 'start_trip' AND subject_kind = 'trip') OR (event_kind = 'arrived' AND subject_kind = 'trip') OR (event_kind = 'change_plan' AND subject_kind = 'trip_purpose_change') OR (event_kind = 'activity_complete' AND subject_kind = 'activity_execution') OR (event_kind = 'activity_leave' AND subject_kind = 'activity_execution')", name='ck_missing_location_event_subject'),
    sa.CheckConstraint("event_kind IN ('start_work', 'start_trip', 'change_plan', 'arrived', 'activity_complete', 'activity_leave', 'end_work')", name='ck_missing_location_event_kind'),
    sa.CheckConstraint("notification_status IN ('pending', 'notified', 'suppressed')", name='ck_missing_location_notification'),
    sa.CheckConstraint("reason_code IN ('permission_denied', 'position_unavailable', 'acquisition_timeout', 'cached_rejected', 'recovery_window_exhausted', 'no_client_report')", name='ck_missing_location_reason'),
    sa.CheckConstraint("subject_kind IN ('work_session', 'trip', 'trip_purpose_change', 'activity_execution')", name='ck_missing_location_subject_kind'),
    sa.CheckConstraint('subject_id > 0', name='ck_missing_location_subject_id'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id', 'company_id'], ['trip.id', 'trip.company_id'], name='fk_missing_location_trip_same_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_session_id', 'company_id'], ['work_session.id', 'work_session.company_id'], name='fk_missing_location_session_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_location_event_id'), 'missing_location_event', ['id'], unique=False)
    op.create_index('ix_missing_location_pending_notice', 'missing_location_event', ['company_id', 'notification_status'], unique=False)
    op.create_index('uq_missing_location_event', 'missing_location_event', ['company_id', 'event_kind', 'subject_kind', 'subject_id'], unique=True)
    op.create_table('trip_mileage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), server_default='pending_calculation', nullable=False),
    sa.Column('total_meters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_reason', sa.String(length=40), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state = 'calculated' AND total_meters IS NOT NULL  AND calculated_at IS NOT NULL AND terminal_reason IS NULL) OR (state <> 'calculated' AND total_meters IS NULL  AND calculated_at IS NULL)", name='ck_trip_mileage_calculated_facts'),
    sa.CheckConstraint("(state IN ('not_calculable', 'calculation_failed')  AND terminal_reason IS NOT NULL) OR (state NOT IN ('not_calculable', 'calculation_failed')  AND (state = 'calculated' OR terminal_reason IS NULL))", name='ck_trip_mileage_terminal_needs_reason'),
    sa.CheckConstraint("state IN ('pending_calculation', 'calculated', 'not_calculable', 'calculation_failed')", name='ck_trip_mileage_state'),
    sa.CheckConstraint("terminal_reason IN ('start_waypoint_missing', 'arrival_waypoint_missing', 'change_plan_waypoint_missing', 'interrupted_without_arrival', 'routing_exhausted', 'implausible_segment')", name='ck_trip_mileage_terminal_reason'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_trip_mileage_attempts'),
    sa.CheckConstraint('total_meters IS NULL OR total_meters >= 0', name='ck_trip_mileage_total_non_negative'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id', 'company_id'], ['trip.id', 'trip.company_id'], name='fk_trip_mileage_trip_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'company_id', name='uq_trip_mileage_trip'),
    sa.UniqueConstraint('id', 'company_id', name='uq_trip_mileage_id_company')
    )
    op.create_index(op.f('ix_trip_mileage_company_id'), 'trip_mileage', ['company_id'], unique=False)
    op.create_index('ix_trip_mileage_due', 'trip_mileage', ['state', 'next_attempt_at'], unique=False, postgresql_where=sa.text("state = 'pending_calculation'"))
    op.create_index(op.f('ix_trip_mileage_id'), 'trip_mileage', ['id'], unique=False)
    op.create_table('trip_mileage_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trip_mileage_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_event_kind', sa.String(length=30), nullable=False),
    sa.Column('from_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('from_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('from_evidence_level', sa.String(length=20), nullable=False),
    sa.Column('from_accuracy_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('from_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_fix_id', sa.Integer(), nullable=True),
    sa.Column('to_event_kind', sa.String(length=30), nullable=False),
    sa.Column('to_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('to_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('to_evidence_level', sa.String(length=20), nullable=False),
    sa.Column('to_accuracy_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('to_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_fix_id', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('provider_version', sa.String(length=40), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('haversine_meters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('distance_meters >= 0', name='ck_trip_mileage_segment_distance'),
    sa.CheckConstraint('from_latitude >= -90 AND from_latitude <= 90 AND to_latitude >= -90 AND to_latitude <= 90 AND from_longitude >= -180 AND from_longitude <= 180 AND to_longitude >= -180 AND to_longitude <= 180', name='ck_trip_mileage_segment_coordinates'),
    sa.CheckConstraint('sequence >= 1', name='ck_trip_mileage_segment_sequence'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_mileage_id', 'company_id'], ['trip_mileage.id', 'trip_mileage.company_id'], name='fk_trip_mileage_segment_parent_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_mileage_id', 'sequence', name='uq_trip_mileage_segment_sequence')
    )
    op.create_index(op.f('ix_trip_mileage_segment_company_id'), 'trip_mileage_segment', ['company_id'], unique=False)
    op.create_index(op.f('ix_trip_mileage_segment_id'), 'trip_mileage_segment', ['id'], unique=False)
    # Hechos observados: se anaden, no se corrigen.
    for tabla in APPEND_ONLY_TABLES:
        op.execute(
            f"""
            CREATE OR REPLACE FUNCTION {tabla}_is_append_only()
            RETURNS trigger AS $BODY$
            BEGIN
                RAISE EXCEPTION '{tabla} is append-only: % is not allowed', TG_OP;
            END;
            $BODY$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{tabla}_append_only
            BEFORE UPDATE OR DELETE ON {tabla}
            FOR EACH ROW EXECUTE FUNCTION {tabla}_is_append_only();
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER trg_{tabla}_no_truncate
            BEFORE TRUNCATE ON {tabla}
            FOR EACH STATEMENT EXECUTE FUNCTION {tabla}_is_append_only();
            """
        )

    # El hecho es inmutable; el estado del aviso avanza. Ver el docstring.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION missing_location_event_is_append_only()
        RETURNS trigger AS $BODY$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION
                    'missing_location_event is append-only: % is not allowed',
                    TG_OP;
            END IF;

            IF (to_jsonb(NEW) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at')
               IS DISTINCT FROM
               (to_jsonb(OLD) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at') THEN
                RAISE EXCEPTION
                    'missing_location_event: only notification fields may change';
            END IF;

            RETURN NEW;
        END;
        $BODY$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_missing_location_event_append_only
        BEFORE UPDATE OR DELETE ON missing_location_event
        FOR EACH ROW EXECUTE FUNCTION missing_location_event_is_append_only();
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_missing_location_event_no_truncate
        BEFORE TRUNCATE ON missing_location_event
        FOR EACH STATEMENT
        EXECUTE FUNCTION missing_location_event_is_append_only();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for tabla in (*APPEND_ONLY_TABLES, "missing_location_event"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tabla}_no_truncate ON {tabla}")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tabla}_append_only ON {tabla}")
        op.execute(f"DROP FUNCTION IF EXISTS {tabla}_is_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_mileage_segment_id'), table_name='trip_mileage_segment')
    op.drop_index(op.f('ix_trip_mileage_segment_company_id'), table_name='trip_mileage_segment')
    op.drop_table('trip_mileage_segment')
    op.drop_index(op.f('ix_trip_mileage_id'), table_name='trip_mileage')
    op.drop_index('ix_trip_mileage_due', table_name='trip_mileage', postgresql_where=sa.text("state = 'pending_calculation'"))
    op.drop_index(op.f('ix_trip_mileage_company_id'), table_name='trip_mileage')
    op.drop_table('trip_mileage')
    op.drop_index('uq_missing_location_event', table_name='missing_location_event')
    op.drop_index('ix_missing_location_pending_notice', table_name='missing_location_event')
    op.drop_index(op.f('ix_missing_location_event_id'), table_name='missing_location_event')
    op.drop_table('missing_location_event')
    op.drop_index('uq_location_fix_event', table_name='location_fix')
    op.drop_index('ix_location_fix_session', table_name='location_fix')
    op.drop_index(op.f('ix_location_fix_id'), table_name='location_fix')
    op.drop_table('location_fix')
    # ### end Alembic commands ###
