"""El hecho Missing, estrictamente inmutable; el aviso, aparte (D-RTE06-MISSING-01).

Revision ID: 0011_strict_missing_fact
Revises: 0010_location_and_mileage
Create Date: 2026-09-30

Que decidio CER, y que corrige
------------------------------
`missing_location_event` guardaba el estado de entrega del aviso
(`notification_status`, `notified_at`) y un `notes` libre. Como ese estado
avanza por definicion, la tabla no podia ser append-only de verdad: llevaba un
disparador que permitia `UPDATE` de esas columnas y rechazaba el resto.

Eso es un hecho "inmutable con excepciones", que es un hecho mutable con pasos
de mas. CER resolvio la ambiguedad hacia el lado estricto: un hecho historico
no se reinterpreta despues. Asi que el estado de entrega se muda a
`missing_location_notification`, que si es operacional, y el hecho pasa a tener
el disparador generico del proyecto: ni `UPDATE`, ni `DELETE`, ni `TRUNCATE`,
sin excepcion de columnas.

El `notes` desaparece y no se sustituye. Un texto libre editable sobre un hecho
historico es exactamente la reinterpretacion que la decision prohibe.

Los datos existentes se mueven, no se pierden
---------------------------------------------
El `INSERT ... SELECT` de abajo crea una fila de entrega por cada hecho que ya
existia, **conservando** su `notification_status` y su `notified_at`. Se hace
antes de borrar las columnas, en la misma transaccion, asi que no hay ventana
en la que el estado no viva en ningun sitio.

El canal es `in_platform` para todas: es el que D-01 exige y el unico que el
esquema anterior podia representar. Poner `email` seria inventar un hecho.

Las filas cuyo `notification_status` no fuera un valor del enum nuevo se
migran como `pending`, y **se cuentan** en el log de la migracion. No deberia
haber ninguna —el `CHECK` anterior lo impedia—, pero si apareciera, dejarla
caer en silencio seria perder el dato.

Un `notes` con contenido **no** se migra a ninguna parte: no hay destino para
el en el modelo nuevo y no se inventa uno. Si hubiera filas con `notes` no
vacio, la migracion las cuenta y lo dice, para que la decision de que hacer con
ese texto sea de quien la lea y no de esta migracion.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011_strict_missing_fact'
down_revision: Union[str, None] = '0010_location_and_mileage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero el unico: la clave foranea compuesta de la tabla nueva lo
    # necesita ya existente. El autogenerate lo ponia despues y el
    # `CREATE TABLE` fallaba.
    op.create_unique_constraint('uq_missing_location_event_id_company', 'missing_location_event', ['id', 'company_id'])
    op.create_table('missing_location_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('missing_location_event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'notified' AND delivered_at IS NOT NULL) OR (status <> 'notified' AND delivered_at IS NULL)", name='ck_missing_location_notification_delivered'),
    sa.CheckConstraint("channel IN ('in_platform', 'email')", name='ck_missing_location_notification_channel_value'),
    sa.CheckConstraint("status IN ('pending', 'notified', 'failed', 'suppressed')", name='ck_missing_location_notification_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_missing_location_notification_attempts'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['missing_location_event_id', 'company_id'], ['missing_location_event.id', 'missing_location_event.company_id'], name='fk_missing_location_notification_event_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('missing_location_event_id', 'channel', name='uq_missing_location_notification_channel')
    )
    op.create_index(op.f('ix_missing_location_notification_company_id'), 'missing_location_notification', ['company_id'], unique=False)
    op.create_index('ix_missing_location_notification_due', 'missing_location_notification', ['company_id', 'status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_missing_location_notification_id'), 'missing_location_notification', ['id'], unique=False)
    op.drop_index(op.f('ix_missing_location_pending_notice'), table_name='missing_location_event')
    op.create_index('ix_missing_location_session', 'missing_location_event', ['company_id', 'work_session_id'], unique=False)
    op.drop_constraint(op.f('ck_missing_location_notification'), 'missing_location_event', type_='check')
    # ── Los datos, antes de borrar las columnas ────────────────────────────
    #
    # Una fila de entrega por hecho existente, con su estado tal como estaba.
    # `in_platform` porque es el unico canal que el esquema anterior podia
    # representar; inventar `email` seria inventar un hecho.
    conexion = op.get_bind()

    raros = conexion.execute(
        sa.text(
            "SELECT count(*) FROM missing_location_event "
            "WHERE notification_status NOT IN "
            "('pending', 'notified', 'failed', 'suppressed')"
        )
    ).scalar()
    con_notas = conexion.execute(
        sa.text(
            "SELECT count(*) FROM missing_location_event "
            "WHERE notes IS NOT NULL AND btrim(notes) <> ''"
        )
    ).scalar()

    conexion.execute(
        sa.text(
            """
            INSERT INTO missing_location_notification
                (company_id, missing_location_event_id, channel, status,
                 attempt_count, delivered_at, created_at, updated_at)
            SELECT
                e.company_id,
                e.id,
                'in_platform',
                CASE
                    WHEN e.notification_status IN
                         ('pending', 'notified', 'failed', 'suppressed')
                    THEN e.notification_status
                    ELSE 'pending'
                END,
                CASE WHEN e.notification_status = 'notified' THEN 1 ELSE 0 END,
                CASE
                    WHEN e.notification_status = 'notified'
                    THEN COALESCE(e.notified_at, e.created_at)
                    ELSE NULL
                END,
                e.created_at,
                now()
            FROM missing_location_event e
            """
        )
    )
    migradas = conexion.execute(
        sa.text("SELECT count(*) FROM missing_location_notification")
    ).scalar()

    print(
        f"0011 | missing_location_event -> notification: {migradas} migradas, "
        f"{raros} con estado desconocido migradas como pending, "
        f"{con_notas} con notas que NO tienen destino en el modelo nuevo"
    )

    op.drop_column('missing_location_event', 'notes')
    op.drop_column('missing_location_event', 'notification_status')
    op.drop_column('missing_location_event', 'notified_at')
    # ── El disparador, ahora sin excepciones ───────────────────────────────
    #
    # Se reemplaza la funcion por la generica del proyecto. Los dos disparadores
    # siguen llamandose igual, asi que `EXPECTED_TRIGGERS` y el test de
    # diagnosticos no cambian: lo que cambia es que ya no hay columnas exentas.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION missing_location_event_is_append_only()
        RETURNS trigger AS $BODY$
        BEGIN
            RAISE EXCEPTION
                'missing_location_event is append-only: % is not allowed',
                TG_OP;
        END;
        $BODY$ LANGUAGE plpgsql;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # La funcion vuelve a permitir avanzar el aviso, porque las columnas
    # vuelven a existir.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION missing_location_event_is_append_only()
        RETURNS trigger AS $BODY$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION
                    'missing_location_event is append-only: % is not allowed',
                    TG_OP;
            END IF;

            IF (to_jsonb(NEW) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at')
               IS DISTINCT FROM
               (to_jsonb(OLD) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at') THEN
                RAISE EXCEPTION
                    'missing_location_event: only notification fields may change';
            END IF;

            RETURN NEW;
        END;
        $BODY$ LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missing_location_event', sa.Column('notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('missing_location_event', sa.Column('notification_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('missing_location_event', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_missing_location_notification'), 'missing_location_event', "notification_status::text = ANY (ARRAY['pending'::character varying, 'notified'::character varying, 'suppressed'::character varying]::text[])")
    op.drop_constraint('uq_missing_location_event_id_company', 'missing_location_event', type_='unique')
    op.drop_index('ix_missing_location_session', table_name='missing_location_event')
    op.create_index(op.f('ix_missing_location_pending_notice'), 'missing_location_event', ['company_id', 'notification_status'], unique=False)
    op.drop_index(op.f('ix_missing_location_notification_id'), table_name='missing_location_notification')
    op.drop_index('ix_missing_location_notification_due', table_name='missing_location_notification', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_missing_location_notification_company_id'), table_name='missing_location_notification')
    # El estado vuelve a la columna antes de que la tabla desaparezca: al
    # reves se perderia.
    op.execute(
        """
        UPDATE missing_location_event e
        SET notification_status = n.status,
            notified_at = n.delivered_at
        FROM missing_location_notification n
        WHERE n.missing_location_event_id = e.id
          AND n.company_id = e.company_id
          AND n.channel = 'in_platform'
        """
    )
    op.drop_table('missing_location_notification')
    # ### end Alembic commands ###
