"""El hecho Missing, estrictamente inmutable; el aviso, aparte (D-RTE06-MISSING-01).

Revision ID: 0011_strict_missing_fact
Revises: 0010_location_and_mileage
Create Date: 2026-09-30

Que decidio CER, y que corrige
------------------------------
`missing_location_event` guardaba el estado de entrega del aviso
(`notification_status`, `notified_at`) y un `notes` libre. Como ese estado
avanza por definicion, la tabla no podia ser append-only de verdad: llevaba un
disparador que permitia `UPDATE` de esas columnas y rechazaba el resto.

Eso es un hecho "inmutable con excepciones", que es un hecho mutable con pasos
de mas. CER resolvio la ambiguedad hacia el lado estricto: un hecho historico
no se reinterpreta despues. Asi que el estado de entrega se muda a
`missing_location_notification`, que si es operacional, y el hecho pasa a tener
el disparador generico del proyecto: ni `UPDATE`, ni `DELETE`, ni `TRUNCATE`,
sin excepcion de columnas.

El `notes` desaparece y no se sustituye. Un texto libre editable sobre un hecho
historico es exactamente la reinterpretacion que la decision prohibe.

Los datos existentes se mueven, no se pierden
---------------------------------------------
El `INSERT ... SELECT` de abajo crea una fila de entrega por cada hecho que ya
existia, **conservando** su `notification_status` y su `notified_at`. Se hace
antes de borrar las columnas, en la misma transaccion, asi que no hay ventana
en la que el estado no viva en ningun sitio.

El canal es `in_platform` para todas: es el que D-01 exige y el unico que el
esquema anterior podia representar. Poner `email` seria inventar un hecho.

Las filas cuyo `notification_status` no fuera un valor del enum nuevo se
migran como `pending`, y **se cuentan** en el log de la migracion. No deberia
haber ninguna —el `CHECK` anterior lo impedia—, pero si apareciera, dejarla
caer en silencio seria perder el dato.

Notas historicas: la migracion **se detiene**, no las descarta
-------------------------------------------------------------
La primera version contaba las filas con `notes` no vacio y las dejaba caer al
borrar la columna, confiando en que el numero en el log bastara. CER lo rechazo,
y con razon: contar algo antes de destruirlo no es preservarlo.

Ahora, si existe **una sola** fila con `notes` no vacio, la migracion **falla**
antes de tocar el esquema y dice exactamente que filas son. El principio es el
de la instruccion de cierre: si no se puede preservar el significado del
contenido sin inventar un modelo de producto nuevo, hay que **fallar de forma
segura y exigir revision explicita** en vez de destruirlo.

* **count = 0** — el caso normal, y el unico en este repositorio: la migracion
  sigue, mueve el estado de notificacion y borra las tres columnas.
* **count > 0** — `RuntimeError` con el numero de filas y la consulta para
  verlas. Alembic corre en una transaccion, asi que **no queda estado a
  medias**: ni la tabla nueva, ni las columnas borradas, ni el disparador
  cambiado.

Como identifica el operador las filas afectadas:

    SELECT id, company_id, event_kind, subject_id, occurred_at, notes
    FROM missing_location_event
    WHERE notes IS NOT NULL AND btrim(notes) <> ''
    ORDER BY company_id, occurred_at;

Como se reanuda: el operador decide que hacer con ese texto —exportarlo, pegarlo
en un `audit_event`, o descartarlo a conciencia—, lo vacia, y vuelve a lanzar la
migracion. En cuanto no queda ninguna nota, el camino es el de `count = 0`. No
hay que deshacer nada porque nada se aplico.

Lo que **no** se hace, y es deliberado: no se crea una funcion de notas
editables para salvar el campo viejo, y no se mete el texto en
`failure_detail` de la tabla de avisos. Eso ultimo seria transformar texto libre
historico en un campo con otro significado, que es justo lo que la instruccion
prohibe.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011_strict_missing_fact'
down_revision: Union[str, None] = '0010_location_and_mileage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero el unico: la clave foranea compuesta de la tabla nueva lo
    # necesita ya existente. El autogenerate lo ponia despues y el
    # `CREATE TABLE` fallaba.
    op.create_unique_constraint('uq_missing_location_event_id_company', 'missing_location_event', ['id', 'company_id'])
    op.create_table('missing_location_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('missing_location_event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'notified' AND delivered_at IS NOT NULL) OR (status <> 'notified' AND delivered_at IS NULL)", name='ck_missing_location_notification_delivered'),
    sa.CheckConstraint("channel IN ('in_platform', 'email')", name='ck_missing_location_notification_channel_value'),
    sa.CheckConstraint("status IN ('pending', 'notified', 'failed', 'suppressed')", name='ck_missing_location_notification_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_missing_location_notification_attempts'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['missing_location_event_id', 'company_id'], ['missing_location_event.id', 'missing_location_event.company_id'], name='fk_missing_location_notification_event_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('missing_location_event_id', 'channel', name='uq_missing_location_notification_channel')
    )
    op.create_index(op.f('ix_missing_location_notification_company_id'), 'missing_location_notification', ['company_id'], unique=False)
    op.create_index('ix_missing_location_notification_due', 'missing_location_notification', ['company_id', 'status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_missing_location_notification_id'), 'missing_location_notification', ['id'], unique=False)
    op.drop_index(op.f('ix_missing_location_pending_notice'), table_name='missing_location_event')
    op.create_index('ix_missing_location_session', 'missing_location_event', ['company_id', 'work_session_id'], unique=False)
    # `IF EXISTS` y no `op.drop_constraint`: esta restricción la creó 0010 y su
    # presencia depende del camino por el que la base llegó hasta aquí. Una
    # migración que se cae porque algo que iba a borrar ya no está es frágil sin
    # ganar nada: lo que importa es que después no exista, y eso se cumple igual.
    op.execute(
        "ALTER TABLE missing_location_event "
        "DROP CONSTRAINT IF EXISTS ck_missing_location_notification"
    )
    # ── Los datos, antes de borrar las columnas ────────────────────────────
    #
    # Una fila de entrega por hecho existente, con su estado tal como estaba.
    # `in_platform` porque es el unico canal que el esquema anterior podia
    # representar; inventar `email` seria inventar un hecho.
    conexion = op.get_bind()

    # ── Preflight: nada se toca si hay contenido historico que perder ──────
    #
    # Va antes de la primera escritura a proposito. Alembic corre en una
    # transaccion, asi que fallar aqui deja la base exactamente como estaba.
    con_notas = conexion.execute(
        sa.text(
            "SELECT count(*) FROM missing_location_event "
            "WHERE notes IS NOT NULL AND btrim(notes) <> ''"
        )
    ).scalar()

    if con_notas:
        raise RuntimeError(
            "\n".join(
                (
                    f"0011 ABORTADA: {con_notas} fila(s) de "
                    "missing_location_event tienen `notes` con contenido, y el "
                    "modelo nuevo no tiene destino para ese texto.",
                    "",
                    "Nada se ha modificado. Para verlas:",
                    "  SELECT id, company_id, event_kind, subject_id, "
                    "occurred_at, notes",
                    "  FROM missing_location_event",
                    "  WHERE notes IS NOT NULL AND btrim(notes) <> ''",
                    "  ORDER BY company_id, occurred_at;",
                    "",
                    "Decide que hacer con ese texto -exportarlo, registrarlo en "
                    "audit_event, o descartarlo a conciencia-, vacia la columna "
                    "y vuelve a lanzar la migracion. No hay nada que deshacer.",
                )
            )
        )

    raros = conexion.execute(
        sa.text(
            "SELECT count(*) FROM missing_location_event "
            "WHERE notification_status NOT IN "
            "('pending', 'notified', 'failed', 'suppressed')"
        )
    ).scalar()
    con_notas = conexion.execute(
        sa.text(
            "SELECT count(*) FROM missing_location_event "
            "WHERE notes IS NOT NULL AND btrim(notes) <> ''"
        )
    ).scalar()

    conexion.execute(
        sa.text(
            """
            INSERT INTO missing_location_notification
                (company_id, missing_location_event_id, channel, status,
                 attempt_count, delivered_at, created_at, updated_at)
            SELECT
                e.company_id,
                e.id,
                'in_platform',
                CASE
                    WHEN e.notification_status IN
                         ('pending', 'notified', 'failed', 'suppressed')
                    THEN e.notification_status
                    ELSE 'pending'
                END,
                CASE WHEN e.notification_status = 'notified' THEN 1 ELSE 0 END,
                CASE
                    WHEN e.notification_status = 'notified'
                    THEN COALESCE(e.notified_at, e.created_at)
                    ELSE NULL
                END,
                e.created_at,
                now()
            FROM missing_location_event e
            """
        )
    )
    migradas = conexion.execute(
        sa.text("SELECT count(*) FROM missing_location_notification")
    ).scalar()

    print(
        f"0011 | missing_location_event -> notification: {migradas} migradas, "
        f"{raros} con estado desconocido migradas como pending"
    )

    op.drop_column('missing_location_event', 'notes')
    op.drop_column('missing_location_event', 'notification_status')
    op.drop_column('missing_location_event', 'notified_at')
    # ── El disparador, ahora sin excepciones ───────────────────────────────
    #
    # Se reemplaza la funcion por la generica del proyecto. Los dos disparadores
    # siguen llamandose igual, asi que `EXPECTED_TRIGGERS` y el test de
    # diagnosticos no cambian: lo que cambia es que ya no hay columnas exentas.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION missing_location_event_is_append_only()
        RETURNS trigger AS $BODY$
        BEGIN
            RAISE EXCEPTION
                'missing_location_event is append-only: % is not allowed',
                TG_OP;
        END;
        $BODY$ LANGUAGE plpgsql;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # La funcion vuelve a permitir avanzar el aviso, porque las columnas
    # vuelven a existir.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION missing_location_event_is_append_only()
        RETURNS trigger AS $BODY$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION
                    'missing_location_event is append-only: % is not allowed',
                    TG_OP;
            END IF;

            IF (to_jsonb(NEW) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at')
               IS DISTINCT FROM
               (to_jsonb(OLD) - 'notification_status' - 'notified_at'
                             - 'notes' - 'updated_at') THEN
                RAISE EXCEPTION
                    'missing_location_event: only notification fields may change';
            END IF;

            RETURN NEW;
        END;
        $BODY$ LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missing_location_event', sa.Column('notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('missing_location_event', sa.Column('notification_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('missing_location_event', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('ck_missing_location_notification'), 'missing_location_event', "notification_status::text = ANY (ARRAY['pending'::character varying, 'notified'::character varying, 'suppressed'::character varying]::text[])")
    op.drop_index('ix_missing_location_session', table_name='missing_location_event')
    op.create_index(op.f('ix_missing_location_pending_notice'), 'missing_location_event', ['company_id', 'notification_status'], unique=False)
    op.drop_index(op.f('ix_missing_location_notification_id'), table_name='missing_location_notification')
    op.drop_index('ix_missing_location_notification_due', table_name='missing_location_notification', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_missing_location_notification_company_id'), table_name='missing_location_notification')
    # El estado vuelve a la columna antes de que la tabla desaparezca: al
    # reves se perderia.
    op.execute(
        """
        UPDATE missing_location_event e
        SET notification_status = n.status,
            notified_at = n.delivered_at
        FROM missing_location_notification n
        WHERE n.missing_location_event_id = e.id
          AND n.company_id = e.company_id
          AND n.channel = 'in_platform'
        """
    )
    op.drop_table('missing_location_notification')
    # El único compuesto, **al final**: mientras la tabla de avisos exista,
    # su clave foránea depende de él y PostgreSQL rechaza el `DROP`
    # (`DependentObjectsStillExistError`). El autogenerate lo ponía antes, y
    # eso hacía imposible bajar de 0011 — lo encontró el test M4.
    op.drop_constraint(
        'uq_missing_location_event_id_company',
        'missing_location_event',
        type_='unique',
    )
    # ### end Alembic commands ###
